spring:
  datasource:
#    url: jdbc:h2:mem:employees;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
#    driver-class-name: org.h2.Driver

#    url: jdbc:p6spy:mysql://localhost:3306/yourdb
    url: jdbc:p6spy:h2:mem:employees;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: root
#    password: yourpassword
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  mybatis:
    type-aliases-package: com.example.employee.model
    mapper-locations: classpath*:mappers/*.xml

  h2:
    console:
      enabled: true
      path: /h2-console

#logging.level:
#  root: INFO

logging:
  level:
    # Enable MyBatis internal logging
    org.apache.ibatis: DEBUG

    com.p6spy: DEBUG
    
    # Optional: log SQL parameter values from JDBC
    java.sql: DEBUG
    jdbc:
      sqlonly: DEBUG
      sqltiming: DEBUG

    # Optional: log your DAO/Mapper package
    com.example.employee.dao: DEBUG

