spring:
  datasource:
    url: jdbc:h2:mem:employees;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mybatis:
    type-aliases-package: com.example.employee.model
    mapper-locations: classpath*:mappers/*.xml


  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  root: INFO
